// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5cwxInYRUGZW0UDClBwBAtrac-1Cx5tI',
    appId: '1:92073823:web:fad3e56f88110fb41b90ea',
    messagingSenderId: '92073823',
    projectId: 'movie-recommendation-flutter',
    authDomain: 'movie-recommendation-flutter.firebaseapp.com',
    storageBucket: 'movie-recommendation-flutter.appspot.com',
    measurementId: 'G-7ED9ZTYW8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtRsBqNBpweNcbvoIng3HoBk_zRZf5VkM',
    appId: '1:92073823:android:1d768f15cdb90d081b90ea',
    messagingSenderId: '92073823',
    projectId: 'movie-recommendation-flutter',
    storageBucket: 'movie-recommendation-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfdq2MT6BSuPhWYCE03-nrpvHeeAPpB0',
    appId: '1:92073823:ios:be3ad8ff7ca053161b90ea',
    messagingSenderId: '92073823',
    projectId: 'movie-recommendation-flutter',
    storageBucket: 'movie-recommendation-flutter.appspot.com',
    iosClientId: '92073823-rblvk5tm6nubl0atg32jdlfe5jc825qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLfdq2MT6BSuPhWYCE03-nrpvHeeAPpB0',
    appId: '1:92073823:ios:be3ad8ff7ca053161b90ea',
    messagingSenderId: '92073823',
    projectId: 'movie-recommendation-flutter',
    storageBucket: 'movie-recommendation-flutter.appspot.com',
    iosClientId: '92073823-rblvk5tm6nubl0atg32jdlfe5jc825qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
